version: "3"

services:

  app:
    container_name: reactapp
    build: ./app
    ports:
      - 8080:3000
    volumes:
      - ./app:/home/app
    depends_on:
      - pg
      - api
      - redis
    env_file:
      - ./app/.env

  api:
    container_name: restapi
    build: ./api
    ports:
      - 8081:3001
    volumes:
      - ./api:/home/app
    depends_on:
      - pg
      - redis
    env_file:
      - ./api/.env

  pg:
    container_name: pg
    image: postgres:14.5
    restart: always
    ports:
      - 5555:5432
    env_file:
      - ./api/.env
    volumes:
      - vol_pg:/var/lib/postgresql/
    depends_on:
      - redis
  
  redis:
    container_name: redis
    image: redis
    ports:
      - 6879:6379

volumes:
  vol_pg:
