
###

POST http://localhost:3001/v1/session/635e83ea12ff3f3244c2e33b
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
  "sessionToken": "-"
}

###

POST http://localhost:3001/v1/session
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
  "sessionToken": "-",
  "data": "{ \"x1\": 2, \"x2\": 2 }"
}

###

DELETE http://localhost:3001/v1/session/63500c4eaa6e4529e0bdcbac
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
  "sessionToken": "-"
}

###

